// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;

import java.util.List;

public class CreateHikeTest {
  private WebDriver driver;
    JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createHike() throws InterruptedException {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1936, 1048));
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("mariannefruehling@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("pfaender1234");
    driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("loggedInUser")).click();
    driver.findElement(By.linkText("Create Hike")).click();
    driver.findElement(By.id("titleInput")).sendKeys("Test Hike Title");
    driver.findElement(By.id("descriptionInput")).sendKeys("Test Hike Description");
    String os = System.getProperty("os.name");
    String filePath;
    if (os.contains("Windows")) {
      filePath = System.getProperty("user.dir") + "\\src\\test\\java\\TestHikeImage.jpg";
    }
    else {
      filePath = System.getProperty("user.dir") + "/src/test/java/TestHikeImage.jpg";
    }
    WebElement imageUpload = driver.findElement(By.id("coverImageInput"));
    imageUpload.sendKeys(filePath);
    WebElement detailsTabElement = driver.findElement(By.id("pills-details-tab"));
    js.executeScript("arguments[0].scrollIntoView(true);", detailsTabElement);
    Thread.sleep(1500);
    driver.findElement(By.id("pills-details-tab")).click();
    driver.findElement(By.id("distanceInput")).sendKeys("8.0");
    driver.findElement(By.id("hoursInput")).sendKeys("2");
    driver.findElement(By.id("minutesInput")).sendKeys("12");
    driver.findElement(By.id("altitudeInput")).sendKeys("120");
    WebElement difficultyInputElement = driver.findElement(By.id("difficultyInput"));
    js.executeScript("arguments[0].scrollIntoView(true);", difficultyInputElement);
    Thread.sleep(1500);
    difficultyInputElement.sendKeys("2");
    difficultyInputElement.click();
    WebElement experienceInputElement = driver.findElement(By.id("experienceInput"));
    js.executeScript("arguments[0].scrollIntoView(true);", experienceInputElement);
    Thread.sleep(1500);
    experienceInputElement.sendKeys("3");
    experienceInputElement.click();
    WebElement landscapeInputElement = driver.findElement(By.id("landscapeInput"));
    js.executeScript("arguments[0].scrollIntoView(true);", landscapeInputElement);
    Thread.sleep(1500);
    landscapeInputElement.sendKeys("4");
    landscapeInputElement.click();
    js.executeScript("window.scrollTo(0, document.body.scrollHeight)");
    Thread.sleep(1500);
    driver.findElement(By.id("optimalSeasonJanuary")).click();
    driver.findElement(By.id("optimalSeasonFebruary")).click();
    driver.findElement(By.id("optimalSeasonMarch")).click();
    WebElement routeTabElement = driver.findElement(By.id("pills-route-tab"));
    js.executeScript("arguments[0].scrollIntoView(true);", routeTabElement);
    Thread.sleep(1500);
    routeTabElement.click();
    driver.findElement(By.id("routeDescriptionInput")).sendKeys("Test Hike Route Description");
    {
      WebElement dropdown = driver.findElement(By.id("regionInput"));
      dropdown.findElement(By.xpath("//option[. = 'Austria - Vorarlberg']")).click();
    }
    WebElement poiTabElement = driver.findElement(By.id("pills-poi-tab"));
    js.executeScript("arguments[0].scrollIntoView(true);", poiTabElement);
    Thread.sleep(1500);
    poiTabElement.click();
    driver.findElement(By.id("startNameInput")).sendKeys("Test Hike Start");
    driver.findElement(By.id("latitudeStartCoordinateInput")).sendKeys("47.458061");
    driver.findElement(By.id("longitudeStartCoordinateInput")).sendKeys("9.772455");
    driver.findElement(By.id("destinationNameInput")).sendKeys("Test Hike Destination");
    driver.findElement(By.id("latitudeDestinationCoordinateInput")).sendKeys("47.463781");
    driver.findElement(By.id("longitudeDestinationCoordinateInput")).sendKeys("9.809005");
    WebElement addPoiButtonElement = driver.findElement(By.id("addPoiButton"));
    js.executeScript("arguments[0].scrollIntoView(true);", addPoiButtonElement);
    Thread.sleep(1500);
    addPoiButtonElement.click();
    Thread.sleep(1500);
    driver.findElement(By.id("poiName")).sendKeys("Test Hike POI");
    {
      WebElement dropdown = driver.findElement(By.id("poiType"));
      dropdown.findElement(By.xpath("//option[. = 'Hut']")).click();
    }
    driver.findElement(By.id("poiLatitude")).sendKeys("47.456654");
    driver.findElement(By.id("poiLongitude")).sendKeys("9.790352");
    driver.findElement(By.id("savePoiButton")).click();
    Thread.sleep(1500);
    WebElement gettingThereTabElement = driver.findElement(By.id("pills-getting-there-tab"));
    js.executeScript("arguments[0].scrollIntoView(true);", gettingThereTabElement);
    Thread.sleep(1500);
    gettingThereTabElement.click();
    driver.findElement(By.id("gettingThereInput")).sendKeys("Test Hike Getting There");
    WebElement saveButtonElement = driver.findElement(By.id("saveButtonNewHike"));
    js.executeScript("arguments[0].scrollIntoView(true);", saveButtonElement);
    Thread.sleep(1500);
    saveButtonElement.click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".toast-body"));
      assert(!elements.isEmpty());
    }
  }
}
