// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;

import java.util.List;

public class CreateHikeTest {
  private WebDriver driver;
    JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createHike() throws InterruptedException {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1936, 1048));
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("mariannefruehling@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("pfaender1234");
    driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("loggedInUser")).click();
    driver.findElement(By.linkText("Create Hike")).click();
    driver.findElement(By.id("titleInput")).click();
    driver.findElement(By.id("titleInput")).sendKeys("Test Hike Title");
    driver.findElement(By.id("descriptionInput")).click();
    driver.findElement(By.id("descriptionInput")).sendKeys("Test Hike Description");
    String filePath = System.getProperty("user.dir") + "\\src\\test\\java\\TestHikeImage.jpg";
    WebElement imageUpload = driver.findElement(By.id("coverImageInput"));
    imageUpload.sendKeys(filePath);
    driver.findElement(By.id("pills-details-tab")).click();
    driver.findElement(By.id("distanceInput")).click();
    driver.findElement(By.id("distanceInput")).sendKeys("8.0");
    driver.findElement(By.id("hoursInput")).click();
    driver.findElement(By.id("hoursInput")).sendKeys("2");
    driver.findElement(By.id("minutesInput")).click();
    driver.findElement(By.id("minutesInput")).sendKeys("12");
    driver.findElement(By.id("altitudeInput")).click();
    driver.findElement(By.id("altitudeInput")).sendKeys("120");
    driver.findElement(By.id("difficultyInput")).sendKeys("2");
    driver.findElement(By.id("difficultyInput")).click();
    driver.findElement(By.id("experienceInput")).sendKeys("3");
    driver.findElement(By.id("experienceInput")).click();
    driver.findElement(By.id("landscapeInput")).sendKeys("4");
    driver.findElement(By.id("landscapeInput")).click();
    // Scrolling down to the month input
    js.executeScript("window.scrollTo(0, document.body.scrollHeight)");
    Thread.sleep(500);
    driver.findElement(By.id("optimalSeasonJanuary")).click();
    driver.findElement(By.id("optimalSeasonFebruary")).click();
    driver.findElement(By.id("optimalSeasonMarch")).click();
    driver.findElement(By.id("pills-route-tab")).click();
    driver.findElement(By.id("routeDescriptionInput")).click();
    driver.findElement(By.id("routeDescriptionInput")).sendKeys("Test Hike Route Description");
    driver.findElement(By.id("regionInput")).click();
    {
      WebElement dropdown = driver.findElement(By.id("regionInput"));
      dropdown.findElement(By.xpath("//option[. = 'Croatia']")).click();
    }
    driver.findElement(By.id("pills-poi-tab")).click();
    driver.findElement(By.id("startNameInput")).click();
    driver.findElement(By.id("startNameInput")).sendKeys("Test Hike Start");
    driver.findElement(By.id("latitudeStartCoordinateInput")).click();
    driver.findElement(By.id("latitudeStartCoordinateInput")).sendKeys("47.458061");
    driver.findElement(By.id("longitudeStartCoordinateInput")).click();
    driver.findElement(By.id("longitudeStartCoordinateInput")).sendKeys("9.772455");
    driver.findElement(By.id("destinationNameInput")).click();
    driver.findElement(By.id("destinationNameInput")).sendKeys("Test Hike Destination");
    driver.findElement(By.id("latitudeDestinationCoordinateInput")).click();
    driver.findElement(By.id("latitudeDestinationCoordinateInput")).sendKeys("47.463781");
    driver.findElement(By.id("longitudeDestinationCoordinateInput")).click();
    driver.findElement(By.id("longitudeDestinationCoordinateInput")).sendKeys("9.809005");
    driver.findElement(By.id("addPoiButton")).click();
    Thread.sleep(500);
    driver.findElement(By.id("poiName")).sendKeys("Test Hike POI");
    driver.findElement(By.id("poiType")).click();
    {
      WebElement dropdown = driver.findElement(By.id("poiType"));
      dropdown.findElement(By.xpath("//option[. = 'Hut']")).click();
    }
    driver.findElement(By.id("poiLatitude")).sendKeys("47.456654");
    driver.findElement(By.id("poiLongitude")).sendKeys("9.790352");
    driver.findElement(By.id("savePoiButton")).click();
    // Scrolling up for switching to getting there tab
    js.executeScript("window.scrollTo(0, 0)");
    Thread.sleep(500);
    driver.findElement(By.id("pills-getting-there-tab")).click();
    driver.findElement(By.id("gettingThereInput")).click();
    driver.findElement(By.id("gettingThereInput")).sendKeys("Test Hike Getting There");
    driver.findElement(By.id("saveButtonNewHike")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".toast-body"));
      assert(!elements.isEmpty());
    }
  }
}
