// Generated by Selenium IDE
import hibernate.facade.FacadeJPA;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;

import java.util.*;

public class DeleteHikeTest {
  private WebDriver driver;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void deleteHike() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("mariannefruehling@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("pfaender1234");
    driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("loggedInUser")).click();
    driver.findElement(By.linkText("Profile")).click();
    driver.findElement(By.linkText("Created Hikes")).click();
    driver.findElement(By.id("deleteHikeButton")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".modal-header"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.cssSelector(".card:nth-child(3) > .row > .col-md-3")).click();
  }
}
