// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;

public class SearchHikeNoResultsTest {
    private WebDriver driver;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void searchHikeResults() {
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(1552, 840));
        driver.findElement(By.id("searchBar")).click();
        driver.findElement(By.id("searchBar")).sendKeys("pfänder");
        driver.findElement(By.id("searchBar")).sendKeys(Keys.ENTER);
        assertThat(driver.findElement(By.cssSelector("strong")).getText(), is("No results found!"));
    }
}
