// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;

public class SearchHikeResultsTest {
  private WebDriver driver;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchHikeResults() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("searchBar")).click();
    driver.findElement(By.id("searchBar")).sendKeys(Keys.ENTER);
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col:nth-child(1) .card-image-top"));
      assert(!elements.isEmpty());
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".col:nth-child(2) .card-image-top"));
      assert(!elements.isEmpty());
    }
  }
}
